{% set version = "4.3.7" %}

package:
  name: platformdirs
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/platformdirs/platformdirs-{{ version }}.tar.gz
  sha256: eb437d586b6a0986388f0d6f74aa0cde27b48d0e3d66843640bfb6bdcdb6e351

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    # See the build-system.requires section of pyproject.toml
    - hatch-vcs >=0.4
    - hatchling >=1.25
  run:
    - python >={{ python_min }}

test:
  imports:
    - platformdirs
  commands:
    - pip check
    - mypy -p platformdirs --ignore-missing-imports
  requires:
    - pip
    - mypy
    - python {{ python_min }}

about:
  home: https://github.com/tox-dev/platformdirs
  summary: A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adament
    - gaborbernat
    - bollwyvl
