{% set name = "platformdirs" %}
{% set version = "2.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/platformdirs-{{ version }}.tar.gz
  sha256: 7535e70dfa32e84d4b34996ea99c5e432fa29a708d0f4e394bbcb2a8faa4f16d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools-scm
    - toml
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - platformdirs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/platformdirs/platformdirs
  summary: A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
  dev_url: https://github.com/platformdirs/platformdirs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - adament
    - gaborbernat
