{% set version = "3.11.0" %}

package:
  name: platformdirs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/platformdirs/platformdirs-{{ version }}.tar.gz
  sha256: cf8ee52a3afdb965072dcc652433e0c7e3e40cf5ea1477cd4b3b1d2eb75495b3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.7
    # See the build-system.requires section of pyproject.toml
    - hatchling >=1.17
    - hatch-vcs >=0.3
  run:
    - python >=3.7
    - typing-extensions >=4.6.3

test:
  imports:
    - platformdirs
  commands:
    - pip check
    - mypy -p platformdirs --ignore-missing-imports
  requires:
    - pip
    - mypy

about:
  home: https://github.com/platformdirs/platformdirs
  summary: A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
  dev_url: https://github.com/platformdirs/platformdirs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adament
    - gaborbernat
    - bollwyvl
