{% set version = "4.3.3" %}

package:
  name: platformdirs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/platformdirs/platformdirs-{{ version }}.tar.gz
  sha256: d4e0b7d8ec176b341fb03cb11ca12d0276faa8c485f9cd218f613840463fc2c0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
    # See the build-system.requires section of pyproject.toml
    - hatch-vcs >=0.4
    - hatchling >=1.25
  run:
    - python >=3.8

test:
  imports:
    - platformdirs
  commands:
    - pip check
    - mypy -p platformdirs --ignore-missing-imports
  requires:
    - pip
    - mypy

about:
  home: https://github.com/tox-dev/platformdirs
  summary: A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adament
    - gaborbernat
    - bollwyvl
