# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.9.0"
  python_check_max: "3.14"

package:
  name: platformdirs
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/platformdirs/platformdirs-${{ version }}.tar.gz
  sha256: d8c98e89c427a101947441c7e77b4cd1c8ea717de6f3885e2aa9c73fce276207

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatch-vcs >=0.5
    - hatchling >=1.27
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
      imports: platformdirs
  - requirements:
      run:
        - mypy
        - python ${{ python_min }}.*
    script:
      - mypy -p platformdirs --ignore-missing-imports --disable-error-code=safe-super ${{ "--exclude=windows" if unix }}

about:
  homepage: https://pypi.org/project/platformdirs
  license_file: LICENSE
  license: MIT
  summary: A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
  repository: https://github.com/tox-dev/platformdirs

extra:
  recipe-maintainers:
    - adament
    - gaborbernat
    - bollwyvl
