# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 4.3.7

package:
  name: platformdirs
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/platformdirs/platformdirs-${{ version }}.tar.gz
  sha256: eb437d586b6a0986388f0d6f74aa0cde27b48d0e3d66843640bfb6bdcdb6e351

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatch-vcs >=0.4
    - hatchling >=1.27
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
      imports: platformdirs
  - requirements:
      run:
        - mypy
        - python ${{ python_min }}
    script:
      - mypy -p platformdirs --ignore-missing-imports

about:
  homepage: https://github.com/tox-dev/platformdirs
  license_file: LICENSE
  license: MIT
  summary: A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".

extra:
  recipe-maintainers:
    - adament
    - gaborbernat
    - bollwyvl
