# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.7.0"

package:
  name: platformdirs
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/platformdirs/platformdirs-${{ version }}.tar.gz
  sha256: fd1a5f8599c85d49b9ac7d6e450bc2f1aaf4a23f1fe86d09952fe20ad365cf36

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatch-vcs >=0.5
    - hatchling >=1.27
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
      imports: platformdirs
  - requirements:
      run:
        - mypy
        - python ${{ python_min }}.*
    script:
      - mypy -p platformdirs --ignore-missing-imports

about:
  homepage: https://github.com/tox-dev/platformdirs
  license_file: LICENSE
  license: MIT
  summary: A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".

extra:
  recipe-maintainers:
    - adament
    - gaborbernat
    - bollwyvl
